// StoryGenerationMode.swift
// SeeSaw — Tier 2 companion app
//
// Controls how stories are generated: on-device LLM, cloud API, or hybrid.

enum StoryGenerationMode: String, CaseIterable, Sendable {
    case onDevice = "onDevice"
    case cloud    = "cloud"
    case hybrid   = "hybrid"

    var displayName: String {
        switch self {
        case .onDevice: return "On-Device"
        case .cloud:    return "Cloud"
        case .hybrid:   return "Hybrid"
        }
    }

    var description: String {
        switch self {
        case .onDevice: return "Stories generated entirely on iPhone. Maximum privacy."
        case .cloud:    return "Stories generated by cloud AI. Requires internet."
        case .hybrid:   return "On-device first, cloud enhancement when available."
        }
    }
}
