// StorySessionRecord.swift
// SeeSaw — SwiftData models for persisting complete story sessions.
//
// StorySessionRecord  — one full session (capture → pipeline → N beats).
// StoryBeatRecord     — one LLM-generated beat plus the child's answer.
// PrivacyMetricsData  — DTO bridging PipelineResult fields into the model init.

import Foundation
import SwiftData

// MARK: - StorySessionRecord

/// Persists a complete interactive story session for the Timeline tab.
/// Stores the privacy-filtered scene image, all pipeline metrics, the full
/// conversation (beats + child answers), and PII-scrub events.
@Model
final class StorySessionRecord {

    // MARK: Identity

    var id: UUID
    var createdAt: Date

    // MARK: Child context

    var childName: String
    var childAge: Int
    var storyMode: String           // "onDevice" | "cloud" | "hybrid"

    // MARK: User interaction

    var isLiked: Bool

    // MARK: Scene capture

    /// Original (unblurred) JPEG captured by the camera.
    @Attribute(.externalStorage) var originalImageData: Data?
    /// Privacy-filtered (faces blurred) JPEG after Stage 1-2 of the pipeline.
    @Attribute(.externalStorage) var capturedImageData: Data?

    // MARK: Privacy pipeline results

    var detectedObjects: [String]   // YOLO label strings
    var sceneLabels: [String]       // VNClassifyImageRequest label strings
    var facesDetected: Int
    var facesBlurred: Int
    var pipelineLatencyMs: Double
    var faceDetectMs: Double
    var blurMs: Double
    var yoloMs: Double
    var sceneClassifyMs: Double
    var piiScrubMs: Double
    var rawDataTransmitted: Bool    // Privacy guarantee — always false

    // MARK: Story metadata

    var isCompleted: Bool           // false if session was interrupted mid-story
    var hadContextRestart: Bool     // true if restartWithSummary fired
    var totalBeats: Int
    var totalPiiTokensRedacted: Int // sum across all beat answers

    // MARK: Beats

    @Relationship(deleteRule: .cascade, inverse: \StoryBeatRecord.session)
    var beats: [StoryBeatRecord]

    // MARK: Init

    init(
        childName: String,
        childAge: Int,
        storyMode: String,
        originalImageData: Data?,
        capturedImageData: Data?,
        metrics: PrivacyMetricsData
    ) {
        id                      = UUID()
        createdAt               = Date()
        self.childName          = childName
        self.childAge           = childAge
        self.storyMode          = storyMode
        isLiked                 = false
        self.originalImageData  = originalImageData
        self.capturedImageData  = capturedImageData
        detectedObjects        = metrics.objects
        sceneLabels            = metrics.scenes
        facesDetected          = metrics.facesDetected
        facesBlurred           = metrics.facesBlurred
        pipelineLatencyMs      = metrics.pipelineLatencyMs
        faceDetectMs           = metrics.faceDetectMs
        blurMs                 = metrics.blurMs
        yoloMs                 = metrics.yoloMs
        sceneClassifyMs        = metrics.sceneClassifyMs
        piiScrubMs             = metrics.piiScrubMs
        rawDataTransmitted     = false
        isCompleted            = false
        hadContextRestart      = false
        totalBeats             = 0
        totalPiiTokensRedacted = 0
        beats                  = []
    }

    // MARK: Computed helpers

    /// Beats in chronological order (by creation timestamp).
    var orderedBeats: [StoryBeatRecord] {
        beats.sorted { $0.timestamp < $1.timestamp }
    }

    /// First story beat text, truncated for use as a list-row snippet.
    var storySnippet: String? {
        guard let first = orderedBeats.first else { return nil }
        return String(first.storyText.prefix(100))
    }

    /// Display-safe child name (falls back to "Child" if empty).
    var displayChildName: String {
        childName.isEmpty ? "Child" : childName
    }

    /// Plain-text export of the full conversation for the native share sheet.
    var shareText: String {
        var lines: [String] = [
            "SeeSaw Story — \(createdAt.formatted(date: .long, time: .omitted))",
            "\(displayChildName)'s Adventure (Age \(childAge))",
            "",
        ]
        for beat in orderedBeats {
            lines.append(beat.storyText)
            lines.append("")
            lines.append("Whisper asked: \(beat.question)")
            if let answer = beat.childAnswer, !answer.isEmpty {
                lines.append("\(displayChildName) said: \"\(answer)\"")
            }
            lines.append("")
        }
        lines.append("🌟 Generated by SeeSaw AI Companion")
        return lines.joined(separator: "\n")
    }
}

// MARK: - StoryBeatRecord

/// One LLM-generated story beat: the AI text, the question, and the child's spoken answer.
@Model
final class StoryBeatRecord {

    // MARK: Identity

    var id: UUID

    /// Global sequence number across the whole session (never resets).
    /// Used to sort beats chronologically even across context restarts.
    var sequenceNumber: Int

    /// Local beat index within the current context window (resets after restartWithSummary).
    var localBeatIndex: Int

    var isInitialBeat: Bool      // true only for the very first beat of the session
    var isContextRestart: Bool   // true for the first beat generated after restartWithSummary

    // MARK: LLM output

    var storyText: String
    var question: String
    var isEnding: Bool

    // MARK: Performance

    var generationMs: Double
    var ttftMs: Double          // time-to-first-token; 0.0 if not captured for this beat

    // MARK: Child response

    var childAnswer: String?
    var answerLength: Int
    var piiTokensRedacted: Int  // tokens scrubbed from this beat's answer

    // MARK: Timestamp

    var timestamp: Date

    // MARK: Relationship

    var session: StorySessionRecord?

    // MARK: Init

    init(
        sequenceNumber: Int,
        localBeatIndex: Int,
        isInitialBeat: Bool,
        isContextRestart: Bool,
        storyText: String,
        question: String,
        isEnding: Bool,
        generationMs: Double,
        ttftMs: Double
    ) {
        id                    = UUID()
        self.sequenceNumber   = sequenceNumber
        self.localBeatIndex   = localBeatIndex
        self.isInitialBeat    = isInitialBeat
        self.isContextRestart = isContextRestart
        self.storyText        = storyText
        self.question         = question
        self.isEnding         = isEnding
        self.generationMs     = generationMs
        self.ttftMs           = ttftMs
        childAnswer           = nil
        answerLength          = 0
        piiTokensRedacted     = 0
        timestamp             = Date()
    }
}

// MARK: - PrivacyMetricsData

/// Lightweight DTO that bridges a `PipelineResult` into the `StorySessionRecord` init
/// without creating a SwiftData dependency inside PipelineResult itself.
/// Memberwise init is synthesized; the convenience init(payload:event:) lives in an extension
/// so the synthesized form remains available for previews and tests.
struct PrivacyMetricsData {
    let objects: [String]
    let scenes: [String]
    let facesDetected: Int
    let facesBlurred: Int
    let pipelineLatencyMs: Double
    let faceDetectMs: Double
    let blurMs: Double
    let yoloMs: Double
    let sceneClassifyMs: Double
    let piiScrubMs: Double
}

extension PrivacyMetricsData {
    init(payload: ScenePayload, event: PrivacyMetricsEvent) {
        self.init(
            objects:           payload.objects,
            scenes:            payload.scene,
            facesDetected:     event.facesDetected,
            facesBlurred:      event.facesBlurred,
            pipelineLatencyMs: event.pipelineLatencyMs,
            faceDetectMs:      event.faceDetectMs,
            blurMs:            event.blurMs,
            yoloMs:            event.yoloMs,
            sceneClassifyMs:   event.sceneClassifyMs,
            piiScrubMs:        event.piiScrubMs
        )
    }
}
